[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = auto

addopts =
    -v
    --strict-markers
    --cov-config=.coveragerc
    --cov-report=term

markers =
    unit: Unit tests
    integration: Integration tests

env =
    DB_NAME=test
    DB_USER=test
    DB_PASSWORD=test
    DB_HOST=localhost
    DB_PORT=5432
    DB_ECHO=False
    REDIS_HOST=localhost
    REDIS_PORT=6379
    REDIS_PASSWORD=test
    REDIS_DB=0
    SERVER_PORT=8080
    CLIENT_PORT=8000
    CLIENT_HOST=localhost
    SECRET_KEY=test-secret-key
    TOKEN_EXPIRE=3600
    SECRET_LINK_KEY=jOlDKyBBqp8okb9sS-E6FzTXyTv0viu3aessVKSdLSU=
    DEFAULT_SECRET_APPLICATION_LINK_PART=submit_professor_application