target-version = "py313"
line-length = 120
indent-width = 4
exclude = ["alembic"]

[lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "B",
    "N",
    "UP",
    "ARG",
    "SIM"
]
ignore = ["N805", "B008", "B904", "ARG002", "SIM102"]


[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false