"""Create proffessors_details table

Revision ID: 8430c4220657
Revises: 3c801be7201d
Create Date: 2026-05-22 21:23:47.735456

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8430c4220657"
down_revision: Union[str, Sequence[str], None] = "3c801be7201d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "professors_details",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("surname", sa.String(length=32), nullable=False),
        sa.Column("patronymic", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("professors_details")
    # ### end Alembic commands ###
