"""Create secret link table

Revision ID: d563b8301c84
Revises: cd9c61321766
Create Date: 2026-06-04 15:38:26.897215

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d563b8301c84"
down_revision: Union[str, Sequence[str], None] = "cd9c61321766"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_link",
        sa.Column("secret_part", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("secret_part ~ '^[a-zA-Z0-9_.-]+$'", name="link_characters_check"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("secret_part"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("application_link")
    # ### end Alembic commands ###
