"""Add section description

Revision ID: 232ff1fea6ba
Revises: 590993941f59
Create Date: 2026-05-13 19:25:05.142758

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "232ff1fea6ba"
down_revision: Union[str, Sequence[str], None] = "590993941f59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sections", sa.Column("description", sa.Text(), nullable=True))

    op.create_check_constraint(
        "section_description_length_check",
        "sections",
        "length(description) <= 500"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("section_description_length_check", "sections", type_="check")
    op.drop_column("sections", "description")
    # ### end Alembic commands ###
