"""Added path to topic content

Revision ID: cd9c61321766
Revises: 7df298f51047
Create Date: 2026-05-28 21:17:36.558933

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cd9c61321766"
down_revision: Union[str, Sequence[str], None] = "7df298f51047"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("topics", sa.Column("topic_directory_path", sa.String(length=255), nullable=False))
    op.create_unique_constraint("topic_path_uq", "topics", ["topic_directory_path"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("topic_path_uq", "topics", type_="unique")
    op.drop_column("topics", "topic_directory_path")
    # ### end Alembic commands ###
