"""Create achievements for students table

Revision ID: 5327dc302e18
Revises: 3425e8c38097
Create Date: 2026-05-08 15:53:20.861716

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5327dc302e18"
down_revision: Union[str, Sequence[str], None] = "3425e8c38097"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "achievements_for_students",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("achievement_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["achievement_id"], ["achievements.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["student_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint(
            "student_id", "achievement_id", name="pq_student_achievement"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("achievements_for_students")
    # ### end Alembic commands ###
