"""Add course description

Revision ID: 590993941f59
Revises: 526022301006
Create Date: 2026-05-10 19:44:03.543641

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "590993941f59"
down_revision: Union[str, Sequence[str], None] = "526022301006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("courses", sa.Column("description", sa.Text(), nullable=True))

    op.create_check_constraint(
        "course_description_length_check",
        "courses",
        "length(description) <= 500"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("course_description_length_check", "courses", type_="check")
    op.drop_column("courses", "description")
    # ### end Alembic commands ###
