"""Unique user-topic for notes

Revision ID: b37b95b91c2b
Revises: 97c816b7196f
Create Date: 2026-05-19 18:09:58.487909

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b37b95b91c2b"
down_revision: Union[str, Sequence[str], None] = "97c816b7196f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_student_topic", "notes",
                                ["student_id", "topic_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_student_topic", "notes", type_="unique")
    # ### end Alembic commands ###
