"""Added tags to object

Revision ID: 3c801be7201d
Revises: 43cb7f079ddf
Create Date: 2026-05-24 12:58:36.243770

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3c801be7201d"
down_revision: Union[str, Sequence[str], None] = "43cb7f079ddf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("courses", sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=False))
    op.create_index("idx_courses_tags_gin", "courses", ["tags"], unique=False, postgresql_using="gin")
    op.add_column("sections", sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=False))
    op.create_index("idx_sections_tags_gin", "sections", ["tags"], unique=False, postgresql_using="gin")
    op.add_column("topics", sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=False))
    op.create_index("idx_topics_tags_gin", "topics", ["tags"], unique=False, postgresql_using="gin")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_topics_tags_gin", table_name="topics", postgresql_using="gin")
    op.drop_column("topics", "tags")
    op.drop_index("idx_sections_tags_gin", table_name="sections", postgresql_using="gin")
    op.drop_column("sections", "tags")
    op.drop_index("idx_courses_tags_gin", table_name="courses", postgresql_using="gin")
    op.drop_column("courses", "tags")
    # ### end Alembic commands ###
