"""Make nickname citext

Revision ID: f15c1b579de8
Revises: 73688a43096a
Create Date: 2026-06-13 09:52:43.842155

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f15c1b579de8"
down_revision: Union[str, Sequence[str], None] = "73688a43096a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.alter_column(
        "users",
        "nickname",
        existing_type=sa.VARCHAR(length=32),
        type_=postgresql.CITEXT(length=32),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "nickname",
        existing_type=postgresql.CITEXT(length=32),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
    )
    op.execute("DROP EXTENSION IF EXISTS citext")
    # ### end Alembic commands ###
