"""Change public fields

Revision ID: 97c816b7196f
Revises: fd597e4b64e8
Create Date: 2026-05-15 12:35:57.298863

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "97c816b7196f"
down_revision: Union[str, Sequence[str], None] = "fd597e4b64e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("courses", sa.Column("is_public", sa.Boolean(), nullable=False))
    op.add_column("courses", sa.Column("is_content_public", sa.Boolean(), nullable=False))
    op.drop_column("courses", "is_open")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("courses", sa.Column("is_open", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column("courses", "is_content_public")
    op.drop_column("courses", "is_public")
    # ### end Alembic commands ###
