"""Added courses resources relation

Revision ID: a5ca5ee5daa2
Revises: 7df298f51047
Create Date: 2026-05-27 17:34:04.899763

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a5ca5ee5daa2"
down_revision: Union[str, Sequence[str], None] = "7df298f51047"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses_resources",
        sa.Column("resource_filename", sa.String(length=512), nullable=False),
        sa.Column("parent_object_id", sa.UUID(), nullable=False),
        sa.Column("parent_object_type", sa.Enum("COURSE", "SECTION", "TOPIC", name="objecttype"), nullable=False),
        sa.PrimaryKeyConstraint("resource_filename"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("courses_resources")
    # ### end Alembic commands ###
