"""Added course ID to topics

Revision ID: 43cb7f079ddf
Revises: b37b95b91c2b
Create Date: 2026-05-21 09:48:52.524866

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "43cb7f079ddf"
down_revision: Union[str, Sequence[str], None] = "b37b95b91c2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("topics", sa.Column("course_id", sa.UUID(), nullable=False))
    op.create_foreign_key("fk_topics_course_id", "topics", "courses", ["course_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_topics_course_id", "topics", type_="foreignkey")
    op.drop_column("topics", "course_id")
    # ### end Alembic commands ###
