"""Added content fields to topics

Revision ID: 7df298f51047
Revises: bcb481288096
Create Date: 2026-05-26 19:42:01.110434

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7df298f51047"
down_revision: Union[str, Sequence[str], None] = "bcb481288096"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("topics", sa.Column("raw_content", postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column("topics", sa.Column("rendered_content", postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("topics", "rendered_content")
    op.drop_column("topics", "raw_content")
    # ### end Alembic commands ###
