"""Add admin comment to application

Revision ID: 8cc6eb13ad1e
Revises: 69658f42c447
Create Date: 2026-05-23 18:51:38.553818

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8cc6eb13ad1e"
down_revision: Union[str, Sequence[str], None] = "69658f42c447"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("professors_applications", sa.Column("admin_comment", sa.String(length=200),
                                                       nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("professors_applications", "admin_comment")
    # ### end Alembic commands ###
