"""Del path to course dir

Revision ID: fd597e4b64e8
Revises: 232ff1fea6ba
Create Date: 2026-05-13 19:28:56.370824

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd597e4b64e8"
down_revision: Union[str, Sequence[str], None] = "232ff1fea6ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "path_to_directory")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "courses", sa.Column("path_to_directory", sa.VARCHAR(length=255), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
