MAX_NOTE_LENGTH = 3000
MAX_COURSE_NAME_LENGTH = 255
MAX_COURSE_DESCRIPTION_LENGTH = 500
MAX_SECTION_DESCRIPTION_LENGTH = 500
ALLOWED_LINK_CHARACTERS = r"^[a-zA-Z0-9_.-]{5,43}$"
MIN_USER_NAME_LENGTH = 4
MAX_USER_NAME_LENGTH = 32
